version: "3"

services:
  db:
    image: mysql:latest
    container_name: db
    tty: true
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - ./.docker/db/mysql:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network: